config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :comment, :presence => true
  validates :author, :presence => true
  validates :points, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, :presence => true
  validates :link, :presence => true
  validates :points, :presence => true
  validates :author, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
    render :new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

private
  def comment_params
    params.require(:comment).permit(:comment, :author, :link)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(points: :desc).limit(5)
    render :index
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

private
  def post_params
    params.require(:post).permit(:title, :link, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@post, @comment] do |f| %>
  <div class="form-row">
    <div class="form-group col-4">
      <%= f.label :comment %>
      <%= f.text_field :comment, :class=>"form-control" %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-4">
      <%= f.label :author %>
      <%= f.text_field :author, :class=>"form-control" %>
    </div>
  </div>
  <p><%= f.submit :class => "btn btn-success" %></p>
<% end %>

app/views/comments/new.html.erb
<h3 class="mt-2">New comment for <%= @post.title %></h3>
<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if @post.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hacker News</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-light bg-secondary mt-4">
        <div class="row ml-1">
          <a href="/"><%= image_tag "y18.gif", :id => "y" %></a>
          <a href="/" id="hackernews" class="mr-1">Hacker News</a> | new | comments | show | ask | jobs | <%= link_to "submit", new_post_path, :class => "ml-1 text-black" %>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render('layouts/errors', :object => @post) %>

<%= form_for @post do |f| %>
  <!-- Post Title -->
  <%= f.label :title %>
  <%= f.text_field :title %>

  <!-- Post Link -->
  <%= f.label :link %>
  <%= f.text_field :link %>

  <!-- Post Author -->
  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/posts/index.html.erb
<div class="card card-body">
  <ol>
    <% @posts.each do |post| %>
      <li><%= image_tag "up-arrow.png", :id => "arrow" %><a href="<%= post.link %>" id="post-title"  class="mr-1"><%= post.title %></a>| <%= link_to "comments", post_path(post), :id => "comments-link" %></li>
      <small class="text-muted"> <%= post.points %> points by <%= post.author %> | <%= post.created_at.strftime("%b. %d @%l:%M %p")%></small>
    <% end %>
  </ol>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="card card-body">
  <h3>Comments for <%= @post.title %></h3>
  <p><%= link_to "Add a comment", new_post_comment_path(@post) %></p>
  <% if @post.comments.any? %>
    <ul>
      <% @post.comments.each do |comment| %>
        <li>
          <%= image_tag "up-arrow.png", :id => "arrow" %>
          <%= comment.comment %>
        </li>
        <small class="text-muted">
          <%= comment.points %> points by <%= comment.author %> | <%= comment.created_at.strftime("%b. %d @%l:%M %p")%>
        </small>
      <% end %>
    </ul>
  <% else %>
    <p>There are no comments yet!</p>
  <% end %>
  <p><%= link_to "Return to Posts", posts_path %></p>
</div>